ckpt_name: "GoogleNet_CUB_PS_G"
db_name: "CUB"
split: "PS"
gpu: "3"
model: "GoogleNet"

test:
    batch_size: 32
    setting: "g"
    epoch: "all"
    imload_mode: "resize_crop"
    self_adaptions: 10
    save_predictions: True

train:
    batch_size: 64
    epochs: 15
    lr_decay: 5
    lr: 1e-4
    beta: 1.67
    log_inter: 64
    ckpt_inter: 1
    data_aug: "resize_random_crop"
    triplet_mode: "batch_hard"
