ckpt_name: "ResNet101_AwA2_PS_G"
db_name: "AwA2"
split: "PS"
gpu: "3"
model: "ResNet101"

test:
    batch_size: 32
    setting: "g"
    epoch: "all"
    imload_mode: "resize_crop"
    self_adaptions: 10
    save_predictions: True

train:
    batch_size: 32
    epochs: 15
    lr_decay: 20
    lr: 1e-5
    beta: 0.7
    log_inter: 32
    ckpt_inter: 1
    data_aug: "resize_random_crop"
    triplet_mode: "batch_hard"
