ckpt_name: "VGG19_CUB_PS_C"
db_name: "CUB"
split: "PS"
gpu: "3"
model: "VGG19"

test:
    batch_size: 32
    setting: "c"
    epoch: "all"
    imload_mode: "resize_crop"
    self_adaptions: 10
    save_predictions: True

train:
    batch_size: 32
    epochs: 15
    lr_decay: 20
    lr: 3e-5
    beta: 5.0
    log_inter: 32
    ckpt_inter: 1
    data_aug: "resize_random_crop"
    triplet_mode: "batch_hard"
